"""RAINY movie mastering. All file paths are server-owned /data artifacts.

This is a *post-production encoder*, NOT neural lip sync. Authentic lip sync
requires an explicit, verified provider and consent for the person's likeness.
"""
from __future__ import annotations
import math
import os
from pathlib import Path
import re
import subprocess
from typing import Optional

PROFILES={
    "720p":{"16:9":(1280,720),"9:16":(720,1280),"1:1":(720,720)},
    "1080p":{"16:9":(1920,1080),"9:16":(1080,1920),"1:1":(1080,1080)},
    "4k":{"16:9":(3840,2160),"9:16":(2160,3840),"1:1":(2160,2160)},
}
MAX_SECONDS={"720p":3600,"1080p":900,"4k":120}
SRT_TIME=re.compile(r"^(\d{2}):(\d{2}):(\d{2}),(\d{3})\s*-->\s*(\d{2}):(\d{2}):(\d{2}),(\d{3})$")

def get_dimensions(profile,aspect_ratio,seconds):
    if profile not in PROFILES or aspect_ratio not in PROFILES[profile]:
        raise ValueError("1080p, 4k, 720p; 9:16, 16:9, 1:1 хэмжээг сонгоно.")
    if isinstance(seconds,bool) or not isinstance(seconds,(int,float)) or not math.isfinite(seconds):
        raise ValueError("Киноны хугацаа буруу байна.")
    if seconds>MAX_SECONDS[profile] or seconds<4:
        raise ValueError(f"{profile} экспорт {MAX_SECONDS[profile]} секунд хүртэл дэмжигдэнэ.")
    if profile=="4k" and os.getenv("RAINY_4K_EXPORT_ENABLED","false").lower()!="true":
        raise ValueError("4K экспорт нөөц/чанарын туршилт дуусаагүй тул идэвхгүй байна.")
    return PROFILES[profile][aspect_ratio]

def parse_srt(text, duration_seconds):
    if not isinstance(text,str) or not 5<=len(text)<=20000:
        raise ValueError("SRT хэмжээ буруу байна.")
    text=text.replace("\r\n","\n").replace("\r","\n").strip()
    blocks=re.split(r"\n\s*\n",text)
    if len(blocks)>600:
        raise ValueError("SRT 600-аас олон реплик байж болохгүй.")
    previous_end=-1.0
    def sec(parts):
        h,m,s,ms=map(int,parts)
        if m>=60 or s>=60 or ms>=1000: raise ValueError("SRT цагийн формат буруу.")
        return 3600*h+60*m+s+ms/1000
    for block in blocks:
        lines=block.strip().split("\n")
        if len(lines)<2: raise ValueError("SRT реплик дутуу байна.")
        timing=lines[1] if lines[0].isdigit() else lines[0]
        match=SRT_TIME.fullmatch(timing.strip())
        if not match: raise ValueError("SRT timestamp буруу байна.")
        st=sec(match.groups()[:4]);en=sec(match.groups()[4:])
        if st<previous_end-0.1 or en<=st or en>duration_seconds+1.1:
            raise ValueError("SRT дараалал/урт видеотой зөрж байна.")
        previous_end=en
        if not " ".join(lines[2:] if lines[0].isdigit() else lines[1:]).strip():
            raise ValueError("SRT бичвэр хоосон байна.")
    return text+"\n"

def owned_music_path(user_id, music_job_id, data_root):
    if not music_job_id: return None
    from . import core
    with core.db() as c:
        row=c.execute("SELECT a.path,a.mime,t.status,t.tool_type FROM artifacts a "
                      "JOIN tool_jobs t ON t.id=a.job_id "
                      "WHERE a.user_id=? AND a.job_id=? AND a.kind='audio' "
                      "ORDER BY a.created DESC LIMIT 1",(user_id,music_job_id)).fetchone()
    if not row or row["status"]!="done" or row["tool_type"] not in {"music","sound_effect","dialogue"}:
        raise ValueError("Хөгжмийн файл таны бүтээл биш эсвэл дуусаагүй байна.")
    path=Path(row["path"]).resolve();root=(data_root/"artifacts").resolve()
    if not path.is_relative_to(root) or not path.is_file() or path.stat().st_size>150*1024*1024:
        raise ValueError("Хөгжмийн файлын байрлал/хэмжээ буруу.")
    if row["mime"] not in {"audio/wav","audio/mpeg","audio/mp3","audio/ogg","audio/flac"}:
        raise ValueError("Хөгжмийн формат зөвшөөрөгдөөгүй.")
    return path

def _safe_run(args,timeout=900):
    try:
        subprocess.run(["ffmpeg","-nostdin","-hide_banner","-loglevel","error","-y",*map(str,args)],
                       check=True,timeout=timeout,stdout=subprocess.DEVNULL,stderr=subprocess.PIPE)
    except subprocess.TimeoutExpired:
        raise ValueError("Видео render timeout. Worker нөөц/хугацааг шалгана уу.")
    except subprocess.CalledProcessError:
        raise ValueError("FFmpeg mastering алдаа. Формат, аудио, хадмал болон worker нөөцийг шалгана уу.")

def master_video(source:Path,output:Path,seconds:float,ratio:str,profile="720p",
                 voice:Optional[Path]=None,music:Optional[Path]=None,srt:Optional[str]=None):
    width,height=get_dimensions(profile,ratio,seconds)
    source=Path(source).resolve();output=Path(output).resolve()
    if not source.is_file(): raise ValueError("Эвлүүлсэн эх видео олдсонгүй.")
    # All paths are generated by our own server. Do not accept arbitrary client paths.
    if output==source or output.suffix!=".mp4":raise ValueError("MP4 гаралтын зам буруу байна.")
    args=["-i",source]
    if voice:
        voice=Path(voice).resolve()
        if not voice.is_file():raise ValueError("Voice track олдсонгүй.")
        args += ["-i",voice]
    if music:
        music=Path(music).resolve()
        if not music.is_file():raise ValueError("Music track олдсонгүй.")
        args += ["-stream_loop","-1","-i",music]
    # Two-pass loudnorm can be expensive in a small CPU worker. A broadcast
    # target is applied here, and the measured LUFS can be verified in QA.
    video=f"scale={width}:{height}:force_original_aspect_ratio=decrease:flags=lanczos,pad={width}:{height}:(ow-iw)/2:(oh-ih)/2,fps=24,format=yuv420p"
    subtitle_path=None
    try:
        if srt:
            text=parse_srt(srt,seconds)
            subtitle_path=output.with_suffix(".srt")
            subtitle_path.write_text(text,encoding="utf-8")
            # Generated filename is hexadecimal or ASCII inside /data/artifacts.
            # Path is never controlled by untrusted prompt text.
            escaped=str(subtitle_path).replace("\\","\\\\").replace(":","\\:").replace("'","\\'")
            video+=f",subtitles=filename='{escaped}'"
        args += ["-filter_complex"]
        f=[]
        if voice:
            f.append("[0:a]volume=0.15[amb]")
            f.append("[1:a]aresample=48000,volume=1.0[spoken]")
            if music:
                f.append("[2:a]aresample=48000,volume=0.32[bgm]")
                f.append("[bgm][spoken]sidechaincompress=threshold=0.07:ratio=7:attack=20:release=350[ducked]")
                f.append("[amb][ducked][spoken]amix=inputs=3:duration=first:dropout_transition=1[mixed]")
            else:
                f.append("[amb][spoken]amix=inputs=2:duration=first:dropout_transition=1[mixed]")
        elif music:
            f.append("[0:a]volume=0.18[amb]")
            f.append("[1:a]aresample=48000,volume=0.45[bgm]")
            f.append("[amb][bgm]amix=inputs=2:duration=first:dropout_transition=1[mixed]")
        else:
            f.append("[0:a]anull[mixed]")
        f.append("[mixed]loudnorm=I=-16:TP=-1.5:LRA=11[mastera]")
        args += [";".join(f),"-map","0:v:0","-map","[mastera]","-vf",video]
        preset="slow" if profile=="720p" else "medium" if profile=="1080p" else "fast"
        crf="17" if profile=="720p" else "18" if profile=="1080p" else "19"
        args += ["-c:v","libx264","-preset",preset,"-crf",crf,"-pix_fmt","yuv420p",
                 "-c:a","aac","-b:a","256k","-ar","48000","-t",str(seconds),
                 "-movflags","+faststart",output]
        _safe_run(args,timeout=1200 if profile=="720p" else 1800 if profile=="1080p" else 2700)
        if not output.is_file() or output.stat().st_size<4096:raise ValueError("Master MP4 бүрэн гарсангүй.")
        return {"export_profile":profile,"export_width":width,"export_height":height,
                "subtitle_burned":bool(srt),"music_attached":bool(music),
                "loudness_target_lufs":-16,"lip_sync":"not_performed",
                "native_4k":False,"note":"4K profile is upscale/export, not native 4K model generation."}
    except Exception:
        output.unlink(missing_ok=True)
        raise
    finally:
        if subtitle_path:subtitle_path.unlink(missing_ok=True)